# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Optional: run tests / lint
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'echo "Optional: run tests here"']

  # Ensure remote directory exists and is owned by target user
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Ensuring remote dir ${_REMOTE_DIR} exists on ${_VM_NAME}"
        gcloud compute ssh --zone="${_ZONE}" "${_TARGET_USER}@${_VM_NAME}" --command "\
          sudo mkdir -p '${_REMOTE_DIR}' && sudo chown -R '${_TARGET_USER}':'${_TARGET_USER}' '${_REMOTE_DIR}' \
        " --quiet

  # Copy workspace files to the VM (use /workspace/*)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Copying source to ${_TARGET_USER}@${_VM_NAME}:${_REMOTE_DIR}"
        gcloud compute scp --recurse --zone="${_ZONE}" /workspace/* "${_TARGET_USER}@${_VM_NAME}:${_REMOTE_DIR}" --quiet

  # SSH to VM and perform deployment (venv, pip install, move service, reload systemd)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Deploying on ${_VM_NAME}..."
        gcloud compute ssh --zone="${_ZONE}" "${_TARGET_USER}@${_VM_NAME}" --command "\
          set -euo pipefail; \
          sudo apt-get update -y || true; \
          sudo apt-get install -y python3 python3-venv python3-pip || true; \
          cd '${_REMOTE_DIR}'; \
          python3 -m venv .venv || true; \
          . .venv/bin/activate; \
          pip install --upgrade pip || true; \
          # install requirements from server/requirements.txt (remote path) \
          if [ -f '${_REMOTE_DIR}/server/requirements.txt' ]; then \
            pip install -r '${_REMOTE_DIR}/server/requirements.txt' || true; \
          fi; \
          # replace placeholder user in the service file and move into systemd \
          if [ -f '${_REMOTE_DIR}/server/${_SERVICE_FILE}' ]; then \
            sed \"s/USER_PLACEHOLDER/${_TARGET_USER}/g\" '${_REMOTE_DIR}/server/${_SERVICE_FILE}' | sudo tee /etc/systemd/system/${_SERVICE_NAME}.service > /dev/null; \
          fi; \
          sudo systemctl daemon-reload; \
          sudo systemctl enable ${_SERVICE_NAME}.service || true; \
          sudo systemctl restart ${_SERVICE_NAME}.service || true; \
          sudo systemctl status ${_SERVICE_NAME}.service --no-pager || true \
        " --quiet

substitutions:
  _VM_NAME: "my-vm"
  _ZONE: "us-central1-a"
  _TARGET_USER: "ubuntu"
  _REMOTE_DIR: "/home/ubuntu/docrec"
  _SERVICE_NAME: "docrec"
  _SERVICE_FILE: "docrec.service"
  _PORT: "8080"
  _GUNICORN_WORKERS: "2"
  _WSGI_MODULE: "app:app"

timeout: "1200s"